set(LIBRARY_TARGET_NAME "GraphiX")

add_library(${LIBRARY_TARGET_NAME} SHARED)
add_library(${PROJECT_NAME}::${LIBRARY_TARGET_NAME} ALIAS ${LIBRARY_TARGET_NAME})
target_sources(${LIBRARY_TARGET_NAME}
    PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/src/adjustMidsideNode.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/AsplitA.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/AsplitL.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/badelems.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/bodyMesh2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/bsort.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/bsortf.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/bsorti.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/calcNormalen.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/calcPrinc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/calcPvector.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/calcWeight.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/checkIfNumber.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/compare.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/compareStrings.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/contact.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/copyEntity.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/corrad.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/dataGeo.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/dataMesh.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/defineEntity.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/dispLists.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/elemChecker.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/extFunktions.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/extGL.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/fillBody2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/foamFaces.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/frecord.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/fuss.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generateTet.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/getGeoDataTria.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/gl3grades.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/graph.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ifind.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/iinsert.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/improveBadTr3.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/improveMesh.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/iniMeshData.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/intpol.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/intpol2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/intpol3.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/iremove.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/linelength.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/m_copy.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/m_prod.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/m_prodtr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/m_sub.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/makeTriFromElems.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/mergEntity.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/mesh2d.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/meshSet.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/meshSurf.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/messages.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/near3d.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/normdist.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/nurbl2seq.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/orient.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/p_angle.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/parser.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pickFunktions.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/plotFunktions.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readAnsysList.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readccx.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readDuns.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readDynaList.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readEdges.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readFoam.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readfrd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readIsaac.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readNastran.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readNG.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readStdCmap.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readstep.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readStl.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readTG.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readVtk.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/readWf.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/rectcyl.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/renumberfrd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/selectDisplayFaces.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/sendMpc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/sendSet.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/setFunktions.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/shapeFunctions.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/sins.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/spline.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/splitElementsToTets.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/stof.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/stoi.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/stopClock.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/stos.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/strfind.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/strsplt.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/surfMesh2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/sword.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/trackball.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/uselibSNL.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/userFunction.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/v_add.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/v_angle_ref.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/v_angle.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/v_betrag.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/v_distA.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/v_matmult.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/v_norm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/v_prod.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/v_rec2cyl.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/v_result.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/v_rot.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/v_scal.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/v_sprod.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/write2aba.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/write2ansys.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/write2aster.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/write2darwin.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/write2dolfyn.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/write2duns.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/write2dyna.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/write2foam.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/write2frd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/write2isaac.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/write2nas.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/write2samcef.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/write2tochnog.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/writebp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/writefbd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/XFunktions.c
    PUBLIC
    FILE_SET HEADERS
    BASE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/include
    FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/include/cgx.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/extUtil.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/trackball.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/uselibSNL.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/xwd.h
)

target_link_libraries(${LIBRARY_TARGET_NAME} PRIVATE SNL)

set(EXE_TARGET_NAME "cgx")
add_executable(${EXE_TARGET_NAME})
target_sources(${EXE_TARGET_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/src/cgx.c)
target_link_libraries(${EXE_TARGET_NAME} PRIVATE ${LIBRARY_TARGET_NAME})
add_dependencies(${EXE_TARGET_NAME} ${LIBRARY_TARGET_NAME})
